update

diff --git a/amlogic-s9xxx/common-files/files/usr/bin/openwrt-backup b/amlogic-s9xxx/common-files/files/usr/bin/openwrt-backup
--- a/amlogic-s9xxx/common-files/files/usr/bin/openwrt-backup
+++ b/amlogic-s9xxx/common-files/files/usr/bin/openwrt-backup
@@ -8,7 +8,8 @@
 #======================================================================
 
 BACKUP_DIR="/.reserved"
-BACKUP_FILE="${BACKUP_DIR}/openwrt_config.tar.gz"
+BACKUP_NAME="openwrt_config.tar.gz"
+BACKUP_FILE="${BACKUP_DIR}/${BACKUP_NAME}"
 BACKUP_LIST='./etc/AdGuardHome.yaml \
 ./etc/adblocklist/ \
 ./etc/amule/ \
@@ -77,6 +78,7 @@ backup() {
     echo -n "Backup config files ... "
     [ -d "${BACKUP_DIR}" ] || mkdir -p "${BACKUP_DIR}"
     eval tar czf "${BACKUP_FILE}" "${BACKUP_LIST}" 2>/dev/null
+    sync
     if [ -f "${BACKUP_FILE}" ];then
         echo "Your config files has been backed up to [ ${BACKUP_FILE} ], please download and save."
         exit 0
@@ -87,13 +89,20 @@ backup() {
 }
 
 restore() {
-    if [ -f "${BACKUP_FILE}" ];then
-	echo -n "restore config files ... "
+    [ -d "${BACKUP_DIR}" ] || mkdir -p "${BACKUP_DIR}"
+    [ -f "/tmp/upload/${BACKUP_NAME}" ] && mv -f "/tmp/upload/${BACKUP_NAME}" ${BACKUP_FILE} && sync
+    [ -f "/mnt/mmcblk*p4/${BACKUP_NAME}" ] && mv -f "/mnt/mmcblk*p4/${BACKUP_NAME}" ${BACKUP_FILE} && sync
+
+    if [ -f "${BACKUP_FILE}" ]; then
+        echo -n "restore config files ... "
         cd /
-        tar xzf "${BACKUP_FILE}"
-	echo "Recovery has been completed using the [ ${BACKUP_FILE} ] file."
+        tar xzf "${BACKUP_FILE}" 2>/dev/null && sync
+
+        echo "Recovery has been completed using the [ ${BACKUP_FILE} ] file. Will start automatically, please refresh later!"
+        sleep 3
+        echo 'b' > /proc/sysrq-trigger
+        exit 0
     else
-        [ -d "${BACKUP_DIR}" ] || mkdir -p "${BACKUP_DIR}"
         echo "The backup file [ ${BACKUP_FILE} ] not found!"
         exit 1
     fi
@@ -102,8 +111,8 @@ restore() {
 gen_fstab() {
     ROOT_MSG=$(lsblk -l -o NAME,PATH,MOUNTPOINT,UUID,FSTYPE,LABEL | awk '$3 ~ /^\/$/ {print $0}')
     if [ "$ROOT_MSG" == "" ];then
-	echo "Get rootfs message failed!"
-	exit 1
+        echo "Get rootfs message failed!"
+        exit 1
     fi
 
     ROOT_NAME=$(echo $ROOT_MSG | awk '{print $1}')
