Optimize the kernel upgrade plan

diff --git a/amlogic-s9xxx/common-files/files/usr/bin/openwrt-kernel b/amlogic-s9xxx/common-files/files/usr/bin/openwrt-kernel
--- a/amlogic-s9xxx/common-files/files/usr/bin/openwrt-kernel
+++ b/amlogic-s9xxx/common-files/files/usr/bin/openwrt-kernel
@@ -163,10 +163,9 @@ extract_kernel() {
 # Support the kernel: boot-*.tar.gz, dtb-amlogic-*.tar.gz, modules-*.tar .gz
 #
 # When the kernel version is upgraded from 5.10 or lower to 5.10 or higher, need to install U-BOOT.
-# Please place the UBOOT_OVERLOAD(name: u-boot.ext) and MAINLINE_UBOOT(name: u-boot.bin.sd.bin) files in the /mnt/mmcblk*p4 directory.
-# When there is no U-BOOT file in this directory, the script will auto try to download the file from the server for completion:
-# UBOOT_OVERLOAD(u-boot.ext): https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/amlogic-s9xxx/amlogic-u-boot"
-# MAINLINE_UBOOT(u-boot.bin.sd.bin): https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/amlogic-s9xxx/common-files/files/lib/u-boot
+# When there is no U-BOOT file in related directory, the script will auto try to download the file from the server for completion:
+# UBOOT_OVERLOAD: https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/amlogic-s9xxx/amlogic-u-boot"
+# MAINLINE_UBOOT: https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/amlogic-s9xxx/common-files/files/lib/u-boot
 
 replace_kernel() {
 
@@ -181,11 +180,6 @@ replace_kernel() {
     # Move kernel related files to the ${P4_PATH} directory
     if  [ $( ls /tmp/upload/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 3 ]; then
         mv -f /tmp/upload/*.tar.gz ${P4_PATH}/ && sync
-    fi
-
-    # Move U-BOOT related files to the ${P4_PATH} directory
-    if  [ $( ls /tmp/upload/u-boot* -l 2>/dev/null | grep "^-" | wc -l ) -ge 1 ]; then
-        mv -f /tmp/upload/u-boot* ${P4_PATH}/ && sync
     fi
 
     if  [ $( ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 3 ]; then
@@ -258,88 +252,85 @@ replace_kernel() {
         V510=0
     fi
 
+    # Check version consistency
     if [ "${V510}" -lt "${K510}" ]; then
-        echo -e "Update to kernel version 5.10 or higher, will to install U-BOOT."
-        sleep 1
-        echo -e "The script will find the U-BOOT relevant files."
-        if [[ ! -s "${P4_PATH}/u-boot.ext" || ! -s "${P4_PATH}/u-boot.bin.sd.bin" ]]; then
+        echo -e "Update to kernel 5.10 or higher, U-BOOT will be installed."
+        if [ -f "/etc/flippy-openwrt-release" ]; then
             # U-BOOT adaptation
-            if [ -f "/etc/flippy-openwrt-release" ]; then
-                source /etc/flippy-openwrt-release 2>/dev/null
-                SOC=${SOC}
-                [ -n "${SOC}" ] || die "Unknown SOC, unable to update."
-                case ${SOC} in
-                    s905x3) UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
-                            MAINLINE_UBOOT="/lib/u-boot/x96maxplus-u-boot.bin.sd.bin" ;;
-                    s905x2) UBOOT_OVERLOAD="u-boot-x96max.bin"
-                            MAINLINE_UBOOT="/lib/u-boot/x96max-u-boot.bin.sd.bin" ;;
-                    s905x)  UBOOT_OVERLOAD="u-boot-p212.bin"
-                            MAINLINE_UBOOT="" ;;
-                    s905d)  UBOOT_OVERLOAD="u-boot-n1.bin"
-                            MAINLINE_UBOOT="" ;;
-                    s912)   UBOOT_OVERLOAD="u-boot-zyxq.bin"
-                            MAINLINE_UBOOT="" ;;
-                    s922x)  UBOOT_OVERLOAD="u-boot-gtkingpro.bin"
-                            MAINLINE_UBOOT="/lib/u-boot/gtkingpro-u-boot.bin.sd.bin" ;;
-                    *)      die "Unknown SOC, unable to update to kernel 5.10 and above." ;;
-                esac
+            source /etc/flippy-openwrt-release 2>/dev/null
+            SOC=${SOC}
+            [ -n "${SOC}" ] || die "Unknown SOC, unable to update."
+            case ${SOC} in
+                s905x3) UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
+                        MAINLINE_UBOOT="/lib/u-boot/x96maxplus-u-boot.bin.sd.bin" ;;
+                s905x2) UBOOT_OVERLOAD="u-boot-x96max.bin"
+                        MAINLINE_UBOOT="/lib/u-boot/x96max-u-boot.bin.sd.bin" ;;
+                s905x)  UBOOT_OVERLOAD="u-boot-p212.bin"
+                        MAINLINE_UBOOT="" ;;
+                s905d)  UBOOT_OVERLOAD="u-boot-n1.bin"
+                        MAINLINE_UBOOT="" ;;
+                s912)   UBOOT_OVERLOAD="u-boot-zyxq.bin"
+                        MAINLINE_UBOOT="" ;;
+                s922x)  UBOOT_OVERLOAD="u-boot-gtkingpro.bin"
+                        MAINLINE_UBOOT="/lib/u-boot/gtkingpro-u-boot.bin.sd.bin" ;;
+                *)      die "Unknown SOC, unable to update to kernel 5.10 and above." ;;
+            esac
 
-                echo -e "Try to download the U-BOOT files from the server."
-                sleep 1
-                GITHUB_RAW="https://raw.githubusercontent.com/ophub/amlogic-s9xxx-openwrt/main/amlogic-s9xxx"
+            GITHUB_RAW="https://raw.githubusercontent.com/ophub/amlogic-s9xxx-openwrt/main/amlogic-s9xxx"
 
-                if [[ -n "${UBOOT_OVERLOAD}" ]]; then
+            # Check ${UBOOT_OVERLOAD}
+            if [[ -n "${UBOOT_OVERLOAD}" ]]; then
+                if [[ ! -s "/boot/${UBOOT_OVERLOAD}" ]]; then
+                    echo -e "Try to download the ${UBOOT_OVERLOAD} file from the server."
                     GITHUB_UBOOT_OVERLOAD="${GITHUB_RAW}/amlogic-u-boot/${UBOOT_OVERLOAD}"
                     #echo -e "UBOOT_OVERLOAD: ${GITHUB_UBOOT_OVERLOAD}"
-                    wget -c "${GITHUB_UBOOT_OVERLOAD}" -O "${P4_PATH}/u-boot.ext" >/dev/null 2>&1 && sync
-                    if [[ "$?" -eq "0" && -s "${P4_PATH}/u-boot.ext" ]]; then
-                        echo -e "The UBOOT_OVERLOAD file download is complete."
+                    wget -c "${GITHUB_UBOOT_OVERLOAD}" -O "/boot/${UBOOT_OVERLOAD}" >/dev/null 2>&1 && sync
+                    if [[ "$?" -eq "0" && -s "/boot/${UBOOT_OVERLOAD}" ]]; then
+                        echo -e "The ${UBOOT_OVERLOAD} file download is complete."
                     else
-                        die "The UBOOT_OVERLOAD file download failed. please try again."
+                        die "The ${UBOOT_OVERLOAD} file download failed. please try again."
                     fi
                 else
-                    die "The 5.10 kernel cannot be used without UBOOT_OVERLOAD."
+                    echo -e "The ${UBOOT_OVERLOAD} files has been found."
                 fi
+            else
+                die "The 5.10 kernel cannot be used without UBOOT_OVERLOAD."
+            fi
 
-                if [[ -n "${MAINLINE_UBOOT}" ]]; then
+            # Check ${MAINLINE_UBOOT}
+            if [[ -n "${MAINLINE_UBOOT}" ]]; then
+                if [[ ! -s "${MAINLINE_UBOOT}" ]]; then
+                    echo -e "Try to download the MAINLINE_UBOOT file from the server."
                     GITHUB_MAINLINE_UBOOT="${GITHUB_RAW}/common-files/files${MAINLINE_UBOOT}"
                     #echo -e "MAINLINE_UBOOT: ${GITHUB_MAINLINE_UBOOT}"
-                    wget -c "${GITHUB_MAINLINE_UBOOT}" -O "${P4_PATH}/u-boot.bin.sd.bin" >/dev/null 2>&1 && sync
-                    if [[ "$?" -eq "0" && -s "${P4_PATH}/u-boot.bin.sd.bin" ]]; then
+                    [ -d "/lib/u-boot" ] || mkdir -p /lib/u-boot
+                    wget -c "${GITHUB_MAINLINE_UBOOT}" -O "${MAINLINE_UBOOT}" >/dev/null 2>&1 && sync
+                    if [[ "$?" -eq "0" && -s "${MAINLINE_UBOOT}" ]]; then
                         echo -e "The MAINLINE_UBOOT file download is complete."
                     else
                         die "The MAINLINE_UBOOT file download failed. please try again."
                     fi
-                else
-                    echo -e "No MAINLINE_UBOOT, ignored."
                 fi
-            else
-                die "The /etc/flippy-openwrt-release file is missing and cannot be upgraded."
             fi
         else
-            echo -e "The U-BOOT files has been found, start to update."
+            die "The /etc/flippy-openwrt-release file is missing and cannot be upgraded."
         fi
 
         # Copy u-boot.ext and u-boot.emmc
-        if [ -f "${P4_PATH}/u-boot.ext" ]; then
-            [ -n "${UBOOT_OVERLOAD}" ] || UBOOT_OVERLOAD="u-boot.ext"
-            cp -f "${P4_PATH}/u-boot.ext" /boot/u-boot.ext && sync && chmod +x /boot/u-boot.ext
-            cp -f "${P4_PATH}/u-boot.ext" /boot/u-boot.emmc && sync && chmod +x /boot/u-boot.emmc
+        if [ -f "/boot/${UBOOT_OVERLOAD}" ]; then
+            cp -f "/boot/${UBOOT_OVERLOAD}" /boot/u-boot.ext && sync && chmod +x /boot/u-boot.ext
+            cp -f "/boot/${UBOOT_OVERLOAD}" /boot/u-boot.emmc && sync && chmod +x /boot/u-boot.emmc
 
             sed -i '/UBOOT_OVERLOAD/d' /etc/flippy-openwrt-release 2>/dev/null
             echo "UBOOT_OVERLOAD='${UBOOT_OVERLOAD}'" >> /etc/flippy-openwrt-release 2>/dev/null
 
-            echo -e "The u-boot.ext file copy is complete."
+            echo -e "The ${UBOOT_OVERLOAD} file copy is complete."
         else
             die "The UBOOT_OVERLOAD file is missing and cannot be upgraded."
         fi
 
         # Write Mainline bootloader
-        if [ -f "${P4_PATH}/u-boot.bin.sd.bin" ]; then
-            [ -d "/lib/u-boot" ] || mkdir /lib/u-boot
-            [ -n "${MAINLINE_UBOOT}" ] || MAINLINE_UBOOT="/lib/u-boot/u-boot.bin.sd.bin"
-            cp -f "${P4_PATH}/u-boot.bin.sd.bin" ${MAINLINE_UBOOT} && sync && chmod +x ${MAINLINE_UBOOT}
-
+        if [ -f "${MAINLINE_UBOOT}" ]; then
             echo -e "Write Mainline bootloader: [ ${MAINLINE_UBOOT} ] to [ /dev/${EMMC_NAME} ]"
             dd if=${MAINLINE_UBOOT} of=/dev/${EMMC_NAME} bs=1 count=442 conv=fsync
             dd if=${MAINLINE_UBOOT} of=/dev/${EMMC_NAME} bs=512 skip=1 seek=1 conv=fsync
