update

diff --git a/amlogic-s9xxx/install-program/files/openwrt-update b/amlogic-s9xxx/install-program/files/openwrt-update
--- a/amlogic-s9xxx/install-program/files/openwrt-update
+++ b/amlogic-s9xxx/install-program/files/openwrt-update
@@ -217,18 +217,25 @@ MODULES_NOW=$(ls ${P2}/lib/modules/ 2>/dev/null)
 VERSION_NOW=$(echo ${MODULES_NOW} | grep -oE '^[1-9].[0-9]{1,2}' 2>/dev/null)
 echo -e "\033[1;32m update from [ ${MODULES_OLD} ] to [ ${MODULES_NOW} ] \033[0m"
 
-#support_emmc_startup info
-source ${P2}/lib/u-boot/support_emmc_startup 2>/dev/null
-FDTFILE=${FDTFILE}
-U_BOOT_EXT=${U_BOOT_EXT}
-UBOOT_OVERLOAD=${UBOOT_OVERLOAD}
-MAINLINE_UBOOT=${MAINLINE_UBOOT}
-ANDROID_UBOOT=${ANDROID_UBOOT}
-AMLOGIC_SOC=${AMLOGIC_SOC}
-KERNEL_VERSION=${KERNEL_VERSION}
+# support_emmc_startup info
+if  [ ! -f ${P2}/lib/u-boot/support_emmc_startup ]; then
+    echo -e "\033[1;31m Missing update information record file: [ ${P2}/lib/u-boot/support_emmc_startup ] \033[0m"
+    exit 1
+else
+    source ${P2}/lib/u-boot/support_emmc_startup 2>/dev/null
+    FDTFILE=${FDTFILE}
+    U_BOOT_EXT=${U_BOOT_EXT}
+    UBOOT_OVERLOAD=${UBOOT_OVERLOAD}
+    MAINLINE_UBOOT=${MAINLINE_UBOOT}
+    ANDROID_UBOOT=${ANDROID_UBOOT}
+    AMLOGIC_SOC=${AMLOGIC_SOC}
+    KERNEL_VERSION=${KERNEL_VERSION}
+    K510=${K510}
+fi
 
-#Check 5.10 kernel mainline bootloader
-if  [[ "${VERSION_NOW}" == "5.10" ]]; then
+# Check 5.10 kernel
+# "${FDTFILE}" != *-sm1-*
+if  [[ "${K510}" -eq "1" ]]; then
     echo -e "\033[1;31m This 5.10 kernel only supports the use of TF/SD cards! \033[0m"
     exit 1
 fi
@@ -407,7 +414,7 @@ chmod 755 ./etc/rc.local*
 
 #Mainline U-BOOT detection
 FLASH_MAINLINE_UBOOT=0
-if  [[ -n "${MAINLINE_UBOOT}" && -f "${P2}${MAINLINE_UBOOT}" && "${IFSHOW_MAINLINE_UBOOT}" -eq 1 ]]; then
+if  [[ -n "${MAINLINE_UBOOT}" && -f "${P2}${MAINLINE_UBOOT}" && "${IFSHOW_MAINLINE_UBOOT}" -eq "1" ]]; then
     cat <<EOF
 ----------------------------------------------------------------------------------
 Found an available mainline bootloader (Mainline u-boot), you can flash into EMMC.
