Sync script update of flippy

diff --git a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-kernel b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-kernel
--- a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-kernel
+++ b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-kernel
@@ -52,24 +52,27 @@ fi
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ];then
+if [ "${ROOT_PTNAME}" == "" ]; then
     echo "Cannot find the partition corresponding to the root file system!"
     exit 1
 fi
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
 case ${ROOT_PTNAME} in
-       mmcblk?p[1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
-                      PARTITION_NAME="p"
-                      LB_PRE="EMMC_"
-                      ;;
-    [hsv]d[a-z][1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
-                      PARTITION_NAME=""
-                      LB_PRE=""
-                      ;;
-                   *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-                      exit 1
-                      ;;
+mmcblk?p[1-4])
+    EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
+    PARTITION_NAME="p"
+    LB_PRE="EMMC_"
+    ;;
+[hsv]d[a-z][1-4])
+    EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
+    PARTITION_NAME=""
+    LB_PRE=""
+    ;;
+*)
+    echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+    exit 1
+    ;;
 esac
 
 echo -e "Current device: ${MYDEVICE_NAME} [ ${MYDTB_FILE} ], Use in [ ${EMMC_NAME} ]"
@@ -80,18 +83,18 @@ P4_PATH="/mnt/${EMMC_NAME}${PARTITION_NAME}4"
 # Move kernel related files to the ${P4_PATH} directory
 mv -f /tmp/upload/* ${P4_PATH}/ 2>/dev/null && sync
 
-if  [ $( ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 3 ]; then
+if [ $(ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l) -ge 3 ]; then
 
-    if  [ $( ls ${P4_PATH}/boot-*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 1 ]; then
-        build_boot=$( ls ${P4_PATH}/boot-*.tar.gz | head -n 1 ) && build_boot=${build_boot##*/}
+    if [ $(ls ${P4_PATH}/boot-*.tar.gz -l 2>/dev/null | grep "^-" | wc -l) -ge 1 ]; then
+        build_boot=$(ls ${P4_PATH}/boot-*.tar.gz | head -n 1) && build_boot=${build_boot##*/}
         echo -e "Update using [ ${build_boot} ] files. Please wait a moment ..."
         flippy_version=${build_boot/boot-/} && flippy_version=${flippy_version/.tar.gz/}
         kernel_version=$(echo ${flippy_version} | grep -oE '^[1-9].[0-9]{1,3}.[0-9]+')
         kernel_vermaj=$(echo ${kernel_version} | grep -oE '^[1-9].[0-9]{1,3}')
         k510_ver=${kernel_vermaj%%.*}
         k510_maj=${kernel_vermaj##*.}
-        if  [ ${k510_ver} -eq "5" ]; then
-            if  [ "${k510_maj}" -ge "10" ]; then
+        if [ ${k510_ver} -eq "5" ]; then
+            if [ "${k510_maj}" -ge "10" ]; then
                 K510=1
             else
                 K510=0
@@ -105,13 +108,13 @@ if  [ $( ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 3 ]; th
         die "Have no boot-*.tar.gz file found in the ${P4_PATH} directory."
     fi
 
-    if  [[ -f ${P4_PATH}/dtb-${MYDTB_FILE}-${flippy_version}.tar.gz ]]; then
+    if [[ -f ${P4_PATH}/dtb-${MYDTB_FILE}-${flippy_version}.tar.gz ]]; then
         build_dtb="dtb-${MYDTB_FILE}-${flippy_version}.tar.gz"
     else
         die "Have no dtb-${MYDTB_FILE}-${flippy_version}.tar.gz file."
     fi
 
-    if  [ -f ${P4_PATH}/modules-${flippy_version}.tar.gz ]; then
+    if [ -f ${P4_PATH}/modules-${flippy_version}.tar.gz ]; then
         build_modules="modules-${flippy_version}.tar.gz"
     else
         die "Have no modules-*.tar.gz file found in the ${P4_PATH} directory."
@@ -138,8 +141,8 @@ MODULES_OLD=$(ls /lib/modules/ 2>/dev/null)
 VERSION_OLD=$(echo ${MODULES_OLD} | grep -oE '^[1-9].[0-9]{1,3}' 2>/dev/null)
 VERSION_ver=${VERSION_OLD%%.*}
 VERSION_maj=${VERSION_OLD##*.}
-if  [ ${VERSION_ver} -eq "5" ]; then
-    if  [ "${VERSION_maj}" -ge "10" ]; then
+if [ ${VERSION_ver} -eq "5" ]; then
+    if [ "${VERSION_maj}" -ge "10" ]; then
         V510=1
     else
         V510=0
@@ -277,21 +280,21 @@ if [[ "${MYDTB_FILE}" == "rockchip" ]]; then
     ln -sf /boot/dtb-${flippy_version} /boot/dtb
 fi
 tar -xzf ${P4_PATH}/${build_dtb} -C /boot/dtb/${MYDTB_FILE} && sync
-[ "$( ls /boot/dtb/${MYDTB_FILE} -l 2>/dev/null | grep "^-" | wc -l )" -ge "1" ] || die "/boot/dtb/${MYDTB_FILE} file is missing."
+[ "$(ls /boot/dtb/${MYDTB_FILE} -l 2>/dev/null | grep "^-" | wc -l)" -ge "1" ] || die "/boot/dtb/${MYDTB_FILE} file is missing."
 echo -e "02. Unpack [ ${build_dtb} ] complete."
 sleep 3
 
 # 03 for /lib/modules/*
 rm -rf /lib/modules/* 2>/dev/null && sync
 tar -xzf ${P4_PATH}/${build_modules} -C /lib/modules && sync
-    cd /lib/modules/${flippy_version}/
-    rm -f *.ko 2>/dev/null
-    find ./ -type f -name '*.ko' -exec ln -s {} ./ \;
-    sync && sleep 3
-        x=$( ls *.ko -l 2>/dev/null | grep "^l" | wc -l )
-        if [ "${x}" -eq "0" ]; then
-            die "Error *.ko Files not found."
-        fi
+cd /lib/modules/${flippy_version}/
+rm -f *.ko 2>/dev/null
+find ./ -type f -name '*.ko' -exec ln -s {} ./ \;
+sync && sleep 3
+x=$(ls *.ko -l 2>/dev/null | grep "^l" | wc -l)
+if [ "${x}" -eq "0" ]; then
+    die "Error *.ko Files not found."
+fi
 echo -e "03. Unpack [ ${build_modules} ] complete."
 sleep 3
 
@@ -299,10 +302,10 @@ rm -rf ${P4_PATH}/dtb-*.tar.gz ${P4_PATH}/boot-*.tar.gz ${P4_PATH}/modules-*.tar
 sync
 
 sed -i '/KERNEL_VERSION/d' /etc/flippy-openwrt-release 2>/dev/null
-echo "KERNEL_VERSION='${kernel_version}'" >> /etc/flippy-openwrt-release 2>/dev/null
+echo "KERNEL_VERSION='${kernel_version}'" >>/etc/flippy-openwrt-release 2>/dev/null
 
 sed -i '/K510/d' /etc/flippy-openwrt-release 2>/dev/null
-echo "K510='${K510}'" >> /etc/flippy-openwrt-release 2>/dev/null
+echo "K510='${K510}'" >>/etc/flippy-openwrt-release 2>/dev/null
 
 sed -i "s/ Kernel.*/ Kernel: ${flippy_version}/g" /etc/banner 2>/dev/null
 
@@ -313,4 +316,3 @@ echo "Successfully updated, automatic restarting..."
 sleep 3
 reboot
 exit 0
-
