openwrt-swap: Increase the remaining space judgment

diff --git a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-swap b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-swap
--- a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-swap
+++ b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-swap
@@ -8,15 +8,13 @@
 #=======================================================================
 
 # Set the swap size in GB
-my_swap_gb=${1}
-if  [[ -n "$(echo "${my_swap_gb}" | sed -n "/^[0-9]\+$/p")" ]]; then
-    swap_gb="${my_swap_gb}"
+my_swap_gb="${1}"
+format_gb="$(echo "${my_swap_gb}" | awk -F "." '{print $1}')"
+if  [[ -n "$(echo "${format_gb}" | sed -n "/^[0-9]\+$/p")" ]]; then
+    swap_gb="${format_gb}"
 else
     swap_gb="1"
 fi
-
-# Operation environment check
-[ -x $0 ] || echo -e "Please grant execution permission: chmod +x $0" && exit 1
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
@@ -40,10 +38,21 @@ case ${ROOT_PTNAME} in
                       ;;
 esac
 
-echo -e "Use in [ ${EMMC_NAME} ]"
+PARTITION_PATH="/mnt/${EMMC_NAME}${PARTITION_NAME}4"
+available_space="$(df -hT ${PARTITION_PATH} | grep '/dev/' | awk '{print $5}' | sed 's/.$//' | awk -F "." '{print $1}')"
+if [ -z "$(echo "${available_space}" | sed -n "/^[0-9]\+$/p")" ]; then
+    echo -e "The path is not available, the remaining space cannot be obtained."
+    exit 1
+fi
+if  [[ "${available_space}" -lt "${swap_gb}" ]]; then
+    echo -e "The remaining space is [ ${available_space} ] GB, and [ ${swap_gb} ] GB swap cannot be created."
+    exit 1
+fi
 
-SWAP_PATH="/mnt/${EMMC_NAME}${PARTITION_NAME}4/.swap"
+SWAP_PATH="${PARTITION_PATH}/.swap"
 mkdir -p ${SWAP_PATH} && sync
+
+echo -e "Prepare to create [ ${swap_gb} ] GB swap in the [ ${SWAP_PATH} ] directory."
 
 # delete current swap
 delete_current_swap() {
@@ -57,8 +66,8 @@ delete_current_swap() {
 # create new swap
 create_new_swap() {
     echo -e "Start creating a new swap..."
-    dd_count=$((1000000*${1}))
-    echo -e "The swap size is: [ ${1} ] GB, Please wait..."
+    dd_count=$((1000000*${swap_gb}))
+    echo -e "The swap size is: [ ${swap_gb} ] GB, Please wait..."
     dd if=/dev/zero of=${SWAP_PATH}/swapfile bs=1024 count=${dd_count} conv=fsync && sync
     chmod 600 ${SWAP_PATH}/swapfile
     mkswap -L SWAP ${SWAP_PATH}/swapfile
