tidy up codes

diff --git a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-backup b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-backup
--- a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-backup
+++ b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-backup
@@ -85,7 +85,7 @@ backup() {
     [ -d "${BACKUP_DIR}" ] || mkdir -p "${BACKUP_DIR}"
     eval tar czf "${BACKUP_FILE}" "${BACKUP_LIST}" 2>/dev/null
     sync
-    if [ -f "${BACKUP_FILE}" ];then
+    if [ -f "${BACKUP_FILE}" ]; then
         echo "Has been backed up to [ ${BACKUP_FILE} ], please download and save."
         exit 0
     else
@@ -97,24 +97,27 @@ backup() {
 restore() {
     # Find the partition where root is located
     ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-    if [ "${ROOT_PTNAME}" == "" ];then
+    if [ "${ROOT_PTNAME}" == "" ]; then
         echo "Cannot find the partition corresponding to the root file system!"
         exit 1
     fi
 
     # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
     case ${ROOT_PTNAME} in
-           mmcblk?p[1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
-                          PARTITION_NAME="p"
-                          LB_PRE="EMMC_"
-                          ;;
-        [hsv]d[a-z][1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
-                          PARTITION_NAME=""
-                          LB_PRE=""
-                          ;;
-                       *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-                          exit 1
-                          ;;
+    mmcblk?p[1-4])
+        EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
+        PARTITION_NAME="p"
+        LB_PRE="EMMC_"
+        ;;
+    [hsv]d[a-z][1-4])
+        EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
+        PARTITION_NAME=""
+        LB_PRE=""
+        ;;
+    *)
+        echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+        exit 1
+        ;;
     esac
 
     [ -d "${BACKUP_DIR}" ] || mkdir -p "${BACKUP_DIR}"
@@ -140,26 +143,29 @@ restore() {
 gen_fstab() {
     # Find the partition where root is located
     ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-    if [ "${ROOT_PTNAME}" == "" ];then
+    if [ "${ROOT_PTNAME}" == "" ]; then
         echo "Cannot find the partition corresponding to the root file system!"
         exit 1
     fi
 
     # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
     case ${ROOT_PTNAME} in
-           mmcblk?p[1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
-                          PARTITION_NAME="p"
-                          ;;
-        [hsv]d[a-z][1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
-                          PARTITION_NAME=""
-                          ;;
-                       *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-                          exit 1
-                          ;;
+    mmcblk?p[1-4])
+        EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
+        PARTITION_NAME="p"
+        ;;
+    [hsv]d[a-z][1-4])
+        EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
+        PARTITION_NAME=""
+        ;;
+    *)
+        echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+        exit 1
+        ;;
     esac
 
     ROOT_MSG=$(lsblk -l -o NAME,PATH,MOUNTPOINT,UUID,FSTYPE,LABEL | awk '$3 ~ /^\/$/ {print $0}')
-    if [ "$ROOT_MSG" == "" ];then
+    if [ "$ROOT_MSG" == "" ]; then
         echo "Get rootfs message failed!"
         exit 1
     fi
@@ -177,7 +183,7 @@ gen_fstab() {
     BOOT_FSTYPE=$(echo $BOOT_MSG | awk '{print $3}')
     BOOT_LABEL=$(echo $BOOT_MSG | awk '{print $4}')
 
-    cat > /etc/config/fstab <<EOF
+    cat >/etc/config/fstab <<EOF
 config global
 	option anon_swap '0'
 	option anon_mount '1'
@@ -194,23 +200,23 @@ config mount
 	option fstype '${ROOT_FSTYPE}'
 EOF
 
-    if [ "${ROOT_FSTYPE}" == "btrfs" ];then
-        echo "	option options 'compress=zstd'" >> /etc/config/fstab
+    if [ "${ROOT_FSTYPE}" == "btrfs" ]; then
+        echo "	option options 'compress=zstd'" >>/etc/config/fstab
     fi
 
-    cat >> /etc/config/fstab <<EOF
+    cat >>/etc/config/fstab <<EOF
 
 config mount
 	option target '/boot'
 EOF
-    
-    if [ "${BOOT_FSTYPE}" == "vfat" ];then
-        echo "	option label '${BOOT_LABEL}'" >> /etc/config/fstab
+
+    if [ "${BOOT_FSTYPE}" == "vfat" ]; then
+        echo "	option label '${BOOT_LABEL}'" >>/etc/config/fstab
     else
-        echo "	option uuid '${BOOT_UUID}'" >> /etc/config/fstab
+        echo "	option uuid '${BOOT_UUID}'" >>/etc/config/fstab
     fi
 
-    cat >> /etc/config/fstab <<EOF
+    cat >>/etc/config/fstab <<EOF
 	option enabled '1'
 	option enabled_fsck '1'
 	option fstype '${BOOT_FSTYPE}'
@@ -243,7 +249,7 @@ create_snapshot() {
         if [ "${nname}" == "" ]; then
             snap_name="${default_snap_name}"
             break
-        elif echo "${nname}" | grep -E "\s+" > /dev/null; then
+        elif echo "${nname}" | grep -E "\s+" >/dev/null; then
             echo "The name [${nname}] contains spaces, please re-enter!"
             continue
         elif [ "${nname}" == "q" ] || [ "${nname}" == "Q" ]; then
@@ -259,14 +265,15 @@ create_snapshot() {
         fi
     done
 
-    (  cd /
-    chattr -ia etc/config/fstab
-    btrfs subvolume snapshot -r /etc "${SNAPSHOT_PRESTR}${snap_name}"
-    if [[ "$?" -eq "0" ]]; then
-        echo "The snapshot is created successfully: ${snap_name}"
-    else
-        echo "Snapshot creation failed!"
-    fi
+    (
+        cd /
+        chattr -ia etc/config/fstab
+        btrfs subvolume snapshot -r /etc "${SNAPSHOT_PRESTR}${snap_name}"
+        if [[ "$?" -eq "0" ]]; then
+            echo "The snapshot is created successfully: ${snap_name}"
+        else
+            echo "Snapshot creation failed!"
+        fi
     )
     read -p "Press [ enter ] to return." q
 }
@@ -279,31 +286,32 @@ restore_snapshot() {
     btrfs subvolume list -rt /
     echo "----------------------------------------------------------------"
     read -p "Please enter the name of the snapshot to be restored (only the part after ${SNAPSHOT_PRESTR} needs to be entered): " snap_name
-    if btrfs subvolume list -rt / | grep "${SNAPSHOT_PRESTR}${snap_name}" > /dev/null; then
+    if btrfs subvolume list -rt / | grep "${SNAPSHOT_PRESTR}${snap_name}" >/dev/null; then
         while :; do
             echo "Once the snapshot is restored, the current [ /etc ] will be overwritten!"
             read -p "Are you sure you want to restore the snapshot: [$snap_name]? y/n [n] " yn
             case $yn in
-                y|Y)
-                    (
-                        cd /
-                        chattr -ia etc/config/fstab
-                        mv etc etc.backup
-                        btrfs subvolume snapshot "${SNAPSHOT_PRESTR}${snap_name}" etc
-                        if [[ "$?" -eq "0" ]]; then
-                            btrfs subvolume delete -c etc.backup
-                            echo "Successfully restored, please enter [ reboot ] to restart the openwrt."
-                        else
-                            rm -rf etc
-                            mv etc.backup etc
-                            echo "Recovery failed, [ etc ] has not changed!"
-                        fi
-                    )
-                    read -p "Press [ enter ] to return." q
-                    break
-                    ;;
-                *)  break
-                    ;;
+            y | Y)
+                (
+                    cd /
+                    chattr -ia etc/config/fstab
+                    mv etc etc.backup
+                    btrfs subvolume snapshot "${SNAPSHOT_PRESTR}${snap_name}" etc
+                    if [[ "$?" -eq "0" ]]; then
+                        btrfs subvolume delete -c etc.backup
+                        echo "Successfully restored, please enter [ reboot ] to restart the openwrt."
+                    else
+                        rm -rf etc
+                        mv etc.backup etc
+                        echo "Recovery failed, [ etc ] has not changed!"
+                    fi
+                )
+                read -p "Press [ enter ] to return." q
+                break
+                ;;
+            *)
+                break
+                ;;
             esac
         done
     else
@@ -324,23 +332,24 @@ delete_snapshot() {
     elif [ "${snap_name}" == "" ]; then
         read -p "Name is empty! Press [ enter ] to return." q
     else
-        if btrfs subvolume list -rt / | grep "${SNAPSHOT_PRESTR}${snap_name}" > /dev/null; then
+        if btrfs subvolume list -rt / | grep "${SNAPSHOT_PRESTR}${snap_name}" >/dev/null; then
             read -p "Are you sure you want to delete ${snap_name}? y/n [n] " yn
             case $yn in
-                y|Y)
-                    (
-                        cd /
-                        btrfs subvolume delete -c "${SNAPSHOT_PRESTR}${snap_name}"
-                        if [[ "$?" -eq "0" ]]; then
-                            echo "Snapshot [ ${snap_name} ] has been deleted."
-                        else
-                            echo "Snapshot [ ${snap_name} ] failed to delete!"
-                        fi
-                    )
-                    read -p "Press [ Enter ] to return." q
-                    ;;
-                *)  break
-                    ;;
+            y | Y)
+                (
+                    cd /
+                    btrfs subvolume delete -c "${SNAPSHOT_PRESTR}${snap_name}"
+                    if [[ "$?" -eq "0" ]]; then
+                        echo "Snapshot [ ${snap_name} ] has been deleted."
+                    else
+                        echo "Snapshot [ ${snap_name} ] failed to delete!"
+                    fi
+                )
+                read -p "Press [ Enter ] to return." q
+                ;;
+            *)
+                break
+                ;;
             esac
         else
             read -p "The name of the snapshot is incorrect, press [ Enter ] to return." q
@@ -349,8 +358,8 @@ delete_snapshot() {
 }
 
 migrate_snapshot() {
-    cur_rootdev=$(lsblk -l -o NAME,MOUNTPOINT |awk '$2~/^\/$/ {print $1}')
-    if [ "${cur_rootdev}" == "" ];then
+    cur_rootdev=$(lsblk -l -o NAME,MOUNTPOINT | awk '$2~/^\/$/ {print $1}')
+    if [ "${cur_rootdev}" == "" ]; then
         echo "The disk device corresponding to the current rootfs cannot be found!"
         read -p "Press [ enter ] to return." q
         return
@@ -358,12 +367,17 @@ migrate_snapshot() {
     dev_pre=$(echo "${cur_rootdev}" | awk '{print substr($1, 1, length($1)-1);}')
     rootdev_idx=$(echo "${cur_rootdev}" | awk '{print substr($1, length($1),1);}')
     case $rootdev_idx in
-        2)  old_rootpath="/mnt/${dev_pre}3";;
-        3)  old_rootpath="/mnt/${dev_pre}2";;
-        *)  echo "Judge the old version of rootfs path failed!"
-            read -p "Press [ enter ] to return." q
-            return
-            ;;
+    2)
+        old_rootpath="/mnt/${dev_pre}3"
+        ;;
+    3)
+        old_rootpath="/mnt/${dev_pre}2"
+        ;;
+    *)
+        echo "Judge the old version of rootfs path failed!"
+        read -p "Press [ enter ] to return." q
+        return
+        ;;
     esac
     echo "The following are snapshots of etc found from the old version of rootfs, please enter the name of one of them."
     echo "Tip: Automatically exclude etc-000 and etc-001"
@@ -371,21 +385,21 @@ migrate_snapshot() {
     btrfs subvolume list -rt "${old_rootpath}" | grep -v "${SNAPSHOT_PRESTR}etc-000" | grep -v "${SNAPSHOT_PRESTR}etc-001"
     echo "-----------------------------------------------------------------------------------"
     read -p "Please enter the name of the snapshot to be migrated (only the part after $(SNAPSHOT_PRESTR) needs to be entered): " old_snap_name
-    if [ "${old_snap_name}" == "" ];then
+    if [ "${old_snap_name}" == "" ]; then
         read -p "The name is empty, Press [ enter ] to return." q
         return
-    elif ! btrfs subvolume list -rt "${old_rootpath}" | awk '{print $4}' | grep "^${SNAPSHOT_PRESTR}${old_snap_name}$" >/dev/null;then
+    elif ! btrfs subvolume list -rt "${old_rootpath}" | awk '{print $4}' | grep "^${SNAPSHOT_PRESTR}${old_snap_name}$" >/dev/null; then
         echo "The name was entered incorrectly, and the corresponding snapshot was not found!"
         read -p "Press [ enter ] to return." q
         return
-    elif [ "${old_snap_name}" == "etc-000" ] || [ "${old_snap_name}" == "etc-001" ];then
+    elif [ "${old_snap_name}" == "etc-000" ] || [ "${old_snap_name}" == "etc-001" ]; then
         echo "Critical snapshots are not allowed to migrate!"
         read -p "Press [ enter ] to return." q
         return
     fi
 
     # Find out if there is a snapshot with the same name under the current rootfs
-    if btrfs subvolume list -rt / | awk '{print $4}' | grep "^\\${SNAPSHOT_PRESTR}${old_snap_name}$" >/dev/null;then
+    if btrfs subvolume list -rt / | awk '{print $4}' | grep "^\\${SNAPSHOT_PRESTR}${old_snap_name}$" >/dev/null; then
         echo "A snapshot with the name [ ${old_snap_name} ] already exists and cannot be migrated! (But you can delete the existing snapshot with the same name and then migrate)"
         read -p "Press [ enter ] to return." q
         return
@@ -398,11 +412,11 @@ migrate_snapshot() {
     echo -e "Note: To migrate the snapshot [ ${old_snap_name} ] of [ ${old_rootpath} ] to the current rootfs, it takes about [ ${need_size} ] space,"
     echo -e "      Please confirm whether the partition [/dev/${cur_rootdev}] where [/] is located has enough free space (Available)?"
     read -p "Are you sure to migrate? y/n [n] " yn
-    if [ "$yn" == "y" ] ||  [ "$yn" == "Y" ];then
+    if [ "$yn" == "y" ] || [ "$yn" == "Y" ]; then
         (
             cd /
             btrfs send ${old_rootpath}/${SNAPSHOT_PRESTR}${old_snap_name} | btrfs receive ${SNAPSHOT_PRESTR}
-            if [ $? -eq 0 ];then
+            if [ $? -eq 0 ]; then
                 btrfs property set -ts ${SNAPSHOT_PRESTR}${old_snap_name} ro false
                 cp ${SNAPSHOT_PRESTR}etc-000/config/fstab ${SNAPSHOT_PRESTR}${old_snap_name}/config/
                 cp ${SNAPSHOT_PRESTR}etc-000/fstab ${SNAPSHOT_PRESTR}${old_snap_name}/
@@ -482,7 +496,7 @@ print_help() {
 }
 
 menu() {
-    while :;do
+    while :; do
         clear
         cat <<EOF
 
@@ -513,38 +527,41 @@ EOF
         echo -ne "please select: [ ]\b\b"
         read select
         case $select in
-            b | backup)            backup;;
-            r | restore)           restore
-                                   gen_fstab;;
-            g | gen_fstab)         gen_fstab;;
-            p | print_list)        print_list;;
-            l | list_snapshot)     list_snapshot;;
-            c | create_snapshot)   create_snapshot;;
-            d | delete_snapshot)   delete_snapshot;;
-            R | restore_snapshot)  restore_snapshot;;
-            m | migrate_snapshot)  migrate_snapshot;;
-            s | snapshot_help)     snapshot_help;;
-            h | help)              print_help;;
-            q | quit)              exit 0;;
+        b | backup) backup ;;
+        r | restore)
+            restore
+            gen_fstab
+            ;;
+        g | gen_fstab) gen_fstab ;;
+        p | print_list) print_list ;;
+        l | list_snapshot) list_snapshot ;;
+        c | create_snapshot) create_snapshot ;;
+        d | delete_snapshot) delete_snapshot ;;
+        R | restore_snapshot) restore_snapshot ;;
+        m | migrate_snapshot) migrate_snapshot ;;
+        s | snapshot_help) snapshot_help ;;
+        h | help) print_help ;;
+        q | quit) exit 0 ;;
         esac
     done
 }
 
 getopts 'brgplcRmsdhq' opts
-case $opts in 
-    b | backup)            backup;;
-    r | restore)           restore
-                           gen_fstab;;
-    g | gen_fstab)         gen_fstab;;
-    p | print_list)        print_list;;
-    l | list_snapshot)     list_snapshot;;
-    c | create_snapshot)   create_snapshot;;
-    d | delete_snapshot)   delete_snapshot;;
-    R | restore_snapshot)  restore_snapshot;;
-    m | migrate_snapshot)  migrate_snapshot;;
-    s | snapshot_help)     snapshot_help;;
-    h | help)              print_help;;
-    q | quit)              exit 0;;
-    *)                     menu;;
+case $opts in
+b | backup) backup ;;
+r | restore)
+    restore
+    gen_fstab
+    ;;
+g | gen_fstab) gen_fstab ;;
+p | print_list) print_list ;;
+l | list_snapshot) list_snapshot ;;
+c | create_snapshot) create_snapshot ;;
+d | delete_snapshot) delete_snapshot ;;
+R | restore_snapshot) restore_snapshot ;;
+m | migrate_snapshot) migrate_snapshot ;;
+s | snapshot_help) snapshot_help ;;
+h | help) print_help ;;
+q | quit) exit 0 ;;
+*) menu ;;
 esac
-
diff --git a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-tf b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-tf
--- a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-tf
+++ b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-tf
@@ -20,47 +20,51 @@ echo -e "${STEPS} Try to create a shared partition ..."
 echo -ne "${STEPS} This operation will clear the data in the remaining space, are you sure to continue? y/n [y]\b\b"
 read yn
 case $yn in
-     n*|N*) echo -e "${ERROR} You aborted the operation!"
-            exit 1
-            ;;
+n* | N*)
+   echo -e "${ERROR} You aborted the operation!"
+   exit 1
+   ;;
 esac
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
 if [ "${ROOT_PTNAME}" == "" ]; then
-    echo -e "${ERROR} Cannot find the partition corresponding to the root file system!"
-    exit 1
+   echo -e "${ERROR} Cannot find the partition corresponding to the root file system!"
+   exit 1
 fi
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
 case ${ROOT_PTNAME} in
-       mmcblk?p[1-4]) DISK_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
-                      PT_PRE="${DISK_NAME}p"
-                      LB_PRE="EMMC_"
-                      ;;
-    [hsv]d[a-z][1-4]) DISK_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
-                      PT_PRE="${DISK_NAME}"
-                      LB_PRE=""
-                      ;;
-                   *) echo -e "${ERROR} Unable to recognize the disk type of ${ROOT_PTNAME}!"
-                      exit 1
-                      ;;
+mmcblk?p[1-4])
+   DISK_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
+   PT_PRE="${DISK_NAME}p"
+   LB_PRE="EMMC_"
+   ;;
+[hsv]d[a-z][1-4])
+   DISK_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
+   PT_PRE="${DISK_NAME}"
+   LB_PRE=""
+   ;;
+*)
+   echo -e "${ERROR} Unable to recognize the disk type of ${ROOT_PTNAME}!"
+   exit 1
+   ;;
 esac
 
 # Get the starting position of the p3 partition
 ROOTFS_MB=960
-START_P3=$( fdisk -l | grep "${ROOT_PTNAME}" | sed -n '$p' | awk '{print $3}' | echo $(($(xargs)+1)) )
+START_P3=$(fdisk -l | grep "${ROOT_PTNAME}" | sed -n '$p' | awk '{print $3}' | echo $(($(xargs) + 1)))
 if [[ -z "${START_P3}" || -z "$(echo ${START_P3} | sed -n "/^[0-9]\+$/p")" ]]; then
-    echo -e "${ERROR} Unable to get starting position!"
-    exit 1
+   echo -e "${ERROR} Unable to get starting position!"
+   exit 1
 fi
-END_P3=$((ROOTFS_MB * 2048 + START_P3 -1))
+END_P3=$((ROOTFS_MB * 2048 + START_P3 - 1))
 
 TOTAL_SIZE=$(lsblk -l -b -o NAME,SIZE | awk "\$1 ~ /^${DISK_NAME}\$/ {print \$2}")
 START_P4=$((END_P3 + 1))
 END_P4=$((TOTAL_SIZE / 512 - 1))
 
-cat > /tmp/fdisk.script <<EOF
+cat >/tmp/fdisk.script <<EOF
 n
 p
 3
@@ -82,10 +86,10 @@ EOF
 sync
 
 echo -e "${STEPS} Fdisk starting ..."
-fdisk /dev/${DISK_NAME} < /tmp/fdisk.script 2>/dev/null
-if [ $? -ne 0 ];then
-	echo -e "${ERROR} fdisk failed!"
-	exit 1
+fdisk /dev/${DISK_NAME} </tmp/fdisk.script 2>/dev/null
+if [ $? -ne 0 ]; then
+   echo -e "${ERROR} fdisk failed!"
+   exit 1
 fi
 sync
 
@@ -96,7 +100,7 @@ mkfs.btrfs -f -L "${LB_PRE}ROOTFS2" "/dev/${PT_PRE}3"
 mount -t btrfs "/dev/${PT_PRE}3" "/mnt/${PT_PRE}3"
 # Create the fourth partition
 mkdir -p /mnt/${PT_PRE}4 && sync
-mkfs.ext4  -F -L "${LB_PRE}SHARED" "/dev/${PT_PRE}4"
+mkfs.ext4 -F -L "${LB_PRE}SHARED" "/dev/${PT_PRE}4"
 mount -t ext4 "/dev/${PT_PRE}4" "/mnt/${PT_PRE}4"
 sync
 
@@ -104,7 +108,7 @@ echo -e "${STEPS} Init the docker config ..."
 rm -rf "/opt/docker" 2>/dev/null && sync
 mkdir -p /mnt/${PT_PRE}4/docker && sync
 ln -sf "/mnt/${PT_PRE}4/docker/" "/opt/docker"
-cat > /etc/docker/daemon.json <<EOF
+cat >/etc/docker/daemon.json <<EOF
 {
   "bip": "172.31.0.1/24",
   "data-root": "/mnt/${PT_PRE}4/docker/",
@@ -131,4 +135,3 @@ echo -e "${SUCCESS} Create partition successfully"
 rm -f /usr/sbin/openwrt-tf 2>/dev/null && sync
 sync
 exit 0
-
