Adjust the installation menu number

diff --git a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-install-amlogic b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-install-amlogic
--- a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-install-amlogic
+++ b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-install-amlogic
@@ -87,31 +87,65 @@ echo "BOOT: ${BOOT_NAME}"
 #Choose the type of installation box
 FDTFILE="meson-sm1-x96-max-plus.dtb"
 U_BOOT_EXT=0
-cat <<EOF
-------------------------------------------------------------------------
-Please select s9xxx box model:
-1. X96-Max+ (4G DDR) -------- [ S905x3 / CPU: 2100Mhz / NETWORK: 1000M ]
-2. X96-Max+ (4G DDR) -------- [ S905x3 / CPU: 2208Mhz / NETWORK: 1000M ]
-3. HK1-Box (4G DDR) --------- [ S905x3 / CPU: 2100Mhz / NETWORK: 1000M ]
-4. HK1-Box (4G DDR) --------- [ S905x3 / CPU: 2208Mhz / NETWORK: 1000M ]
-5. H96-Max-X3 (4G DDR) ------ [ S905x3 / CPU: 2100Mhz / NETWORK: 1000M ]
-6. H96-Max-X3 (4G DDR) ------ [ S905x3 / CPU: 2208Mhz / NETWORK: 1000M ]
-7. Ugoos-X3 (Cube/Pro/Plus) - [ S905x3 / CPU: 2100Mhz / NETWORK: 1000M ]
-8. Ugoos-X3 (Cube/Pro/Plus) - [ S905x3 / CPU: 2208Mhz / NETWORK: 1000M ]
-9. X96-Max-4G --------------- [ S905x2 / CPU: 1908Mhz / NETWORK: 1000M ]
-10. X96-Max-2G -------------- [ S905x2 / CPU: 1908Mhz / NETWORK: 100M  ]
-11. Belink-GT-King ---------- [ S922x  / CPU: 2016Mhz / NETWORK: 1000M ]
-12. Belink-GT-King-Pro ------ [ S922x  / CPU: 2208Mhz / NETWORK: 1000M ]
-13. UGOOS-AM6-Plus ---------- [ S922x  / CPU: 2124Mhz / NETWORK: 1000M ]
-14. ODROID-N2 --------------- [ S922x  / CPU: 2124Mhz / NETWORK: 1000M ]
-15. Octopus-Planet ---------- [ S912   / CPU: 1512Mhz / NETWORK: 1000M ]
-16. Phicomm-n1 -------------- [ S905d  / CPU: 1512Mhz / NETWORK: 1000M ]
-17. hg680p & b860h ---------- [ S905x  / CPU: 1512Mhz / NETWORK: 1000M ]
-18. X96-Mini & TX3-Mini ----- [ S905w  / CPU: 1512Mhz / NETWORK: 100M  ]
 
-0. Other ---------------- [ Enter the dtb file name of your box ]
-------------------------------------------------------------------------
-EOF
+# box model database
+# The field separator is :
+# " " or "" or NA or NULL means this field is null 
+# The fields list:
+# 1.  id
+# 2.  model name
+# 3.  soc
+# 4.  FDTFILE
+# 5.  UBOOT_OVERLOAD
+# 6.  MAINLINE_UBOOT
+# 7.  ANDROID_UBOOT
+# 8.  brief description
+#
+
+model_database="
+# Amlogic GXL Family
+11:Phicomm N1:s905d:meson-gxl-s905d-phicomm-n1.dtb:u-boot-n1.bin:NA:/lib/u-boot/u-boot-2015-phicomm-n1.bin:4C@1512Mhz,2GB Mem,1Gb Net,Wifi
+12:hg680p & b860h:s905x:meson-gxl-s905x-p212.dtb:u-boot-p212.bin:NA:NA:4C@1512Mhz,1Gb net
+13:X96-Mini & TX3-Mini:s905w:meson-gxl-s905w-tx3-mini.dtb:u-boot-s905x-s912.bin:NA:NA:4C@1512Mhz,100M Net
+# Amlogic GXM Family
+21:Octopus Planet:s912:meson-gxm-octopus-planet.dtb:u-boot-zyxq.bin:NA:NA:4C@1512Mhz+4C@1000Mhz,2GB Mem,1Gb Net
+# Amlogic G12A Family
+31:X96 Max 4GB:s905x2:meson-g12a-x96-max.dtb:u-boot-x96max.bin:/lib/u-boot/x96max-u-boot.bin.sd.bin:NA:4C@1908Mhz,4GB Mem,1Gb Net
+32:X96 Max 2GB:s905x2:meson-g12a-x96-max-rmii.dtb:u-boot-x96max.bin:/lib/u-boot/x96max-u-boot.bin.sd.bin:NA:4C@1908Mhz,2GB Mem,100M Net
+# Amlogic G12B Family
+41:Beelink GT-King:s922x:meson-g12b-gtking.dtb:u-boot-gtking.bin:/lib/u-boot/gtking-u-boot.bin.sd.bin:NA:2C@1800Mhz(A53)+4C@1908Mhz(A73),4GB Mem,1Gb Net,Wifi
+42:Beelink GT-King Pro:s922x:meson-g12b-gtking-pro.dtb:u-boot-gtkingpro.bin:/lib/u-boot/gtkingpro-u-boot.bin.sd.bin:NA:2C@1800Mhz(A53)+4C@1908Mhz(A73),4GB Mem,1Gb Net,Wifi
+43:Beelink GT-King Pro H:s922x:meson-g12b-gtking-pro-h.dtb:u-boot-gtkingpro.bin:/lib/u-boot/gtkingpro-u-boot.bin.sd.bin:NA:S922X-H,2C@1800Mhz(A53)+4C@2208Mhz(A73),4GB Mem,1Gb Net,Wifi
+44:Beelink GT-King Pro Rev_A:s922x:meson-g12b-gtking-pro-rev_a.dtb:u-boot-odroid-n2.bin::NA:2C@1800Mhz(A53)+4C@1908Mhz(A73),4GB Mem,1Gb Net,Wifi
+45:Hardkernel ODroid N2:s922x:meson-g12b-odroid-n2.dtb:u-boot-odroid-n2.bin:/lib/u-boot/odroid-n2-u-boot.bin.sd.bin:NA:2C@1800Mhz(A53)+4C@1908Mhz(A73),4GB Mem,1Gb Net
+46:UGOOS AM6 Plus:s922x:meson-g12b-ugoos-am6.dtb:u-boot-gtkingpro.bin:/lib/u-boot/gtkingpro-u-boot.bin.sd.bin:NA:2C@1800Mhz(A53)+4C@1908Mhz(A73),4GB Mem,1Gb Net,Wifi
+# Amlogic SM1 Family
+51:X96 Max+:s905x3:meson-sm1-x96-max-plus.dtb:u-boot-x96maxplus.bin:/lib/u-boot/x96maxplus-u-boot.bin.sd.bin:/lib/u-boot/hk1box-bootloader.img:4C@2100Mhz,4GB Mem,1Gb Net
+52:X96 Max+ (OverClock):s905x3:meson-sm1-x96-max-plus-oc.dtb:u-boot-x96maxplus.bin:/lib/u-boot/x96maxplus-u-boot.bin.sd.bin:/lib/u-boot/hk1box-bootloader.img:4C@2208Mhz,4GB Mem,1Gb Net
+53:HK1 Box:s905x3:meson-sm1-hk1box-vontar-x3.dtb:u-boot-x96maxplus.bin:/lib/u-boot/hk1box-u-boot.bin.sd.bin:NA:4C@2100Mhz,4GB Mem,1Gb Net,Wifi
+54:HK1 Box (OveClock):s905x3:meson-sm1-hk1box-vontar-x3-oc.dtb:u-boot-x96maxplus.bin:/lib/u-boot/hk1box-u-boot.bin.sd.bin:NA:4C@2208Mhz,4GB Mem,1Gb Net,Wifi
+55:H96 Max X3:s905x3:meson-sm1-h96-max-x3.dtb:u-boot-x96maxplus.bin:/lib/u-boot/h96maxx3-u-boot.bin.sd.bin:NA:4C@2100Mhz,4GB Mem,1Gb Net,Wifi
+56:H96 Max X3:s905x3:meson-sm1-h96-max-x3-oc.dtb:u-boot-x96maxplus.bin:/lib/u-boot/h96maxx3-u-boot.bin.sd.bin:NA:4C@2208Mhz,4GB Mem,1Gb Net,Wifi
+57:Ugoos X3:s905x3:meson-sm1-ugoos-x3.dtb:u-boot-ugoos-x3.bin:NA:NA:4C@2100Mhz,2(Cube)/4(Pro,Plus)GB Mem,1Gb Net,Wifi
+58:Ugoos X3(OverClock):s905x3:meson-sm1-ugoos-x3.dtb:u-boot-ugoos-x3.bin:NA:NA:4C@2208Mhz,2(Cube)/4(Pro,Plus)GB Mem,1Gb Net,Wifi
+# Other
+0:Other::NA:NA:NA:NA:Enter the dtb file name of your box
+"
+
+function display_database() {
+    echo "${model_database}" | perl -ne 'chomp;if(m/^#/){s/#\s+//;print "$_ >>>\n"; } elsif($_){ my @f=split/:/; printf("%4d. %-30s%-8s%-s\n", $f[0],$f[1],$f[2],$f[7])}'
+}
+
+function search_model() {
+    local id=$1
+    echo "${model_database}" | awk -F ':' "\$1~/^$id\$/ {print \$0}"
+}
+
+echo "Please select s9xxx box model:"
+echo "----------------------------------------------------------------------------------------------------"
+display_database
+echo "----------------------------------------------------------------------------------------------------"
+
 # For [luci-app-amlogic] input parameter: SOC & DTB
 # When there is no input parameter, select manually
 if [[ -n "${SPECIFY_SOC}" ]]; then
@@ -120,137 +154,44 @@ else
     echo  "Please choose:"
     read  boxtype
 fi
-case  $boxtype in
-      1) FDTFILE="meson-sm1-x96-max-plus.dtb"
-         UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
-         MAINLINE_UBOOT="/lib/u-boot/x96maxplus-u-boot.bin.sd.bin"
-         ANDROID_UBOOT="/lib/u-boot/hk1box-bootloader.img"
-         AMLOGIC_SOC="s905x3"
-         ;;
-      2) FDTFILE="meson-sm1-x96-max-plus-oc.dtb"
-         UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
-         MAINLINE_UBOOT="/lib/u-boot/x96maxplus-u-boot.bin.sd.bin"
-         ANDROID_UBOOT="/lib/u-boot/hk1box-bootloader.img"
-         AMLOGIC_SOC="s905x3"
-         ;;
-      3) FDTFILE="meson-sm1-hk1box-vontar-x3.dtb"
-         UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
-         MAINLINE_UBOOT="/lib/u-boot/hk1box-u-boot.bin.sd.bin"
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s905x3"
-         ;;
-      4) FDTFILE="meson-sm1-hk1box-vontar-x3-oc.dtb"
-         UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
-         MAINLINE_UBOOT="/lib/u-boot/hk1box-u-boot.bin.sd.bin"
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s905x3"
-         ;;
-      5) FDTFILE="meson-sm1-h96-max-x3.dtb"
-         UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
-         MAINLINE_UBOOT="/lib/u-boot/h96maxx3-u-boot.bin.sd.bin"
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s905x3"
-         ;;
-      6) FDTFILE="meson-sm1-h96-max-x3-oc.dtb"
-         UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
-         MAINLINE_UBOOT="/lib/u-boot/h96maxx3-u-boot.bin.sd.bin"
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s905x3"
-         ;;
-      7) FDTFILE="meson-sm1-ugoos-x3.dtb"
-         UBOOT_OVERLOAD="u-boot-ugoos-x3.bin"
-         MAINLINE_UBOOT=""
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s905x3"
-         ;;
-      8) FDTFILE="meson-sm1-ugoos-x3-oc.dtb"
-         UBOOT_OVERLOAD="u-boot-ugoos-x3.bin"
-         MAINLINE_UBOOT=""
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s905x3"
-         ;;
-      9) FDTFILE="meson-g12a-x96-max.dtb"
-         UBOOT_OVERLOAD="u-boot-x96max.bin"
-         MAINLINE_UBOOT="/lib/u-boot/x96max-u-boot.bin.sd.bin"
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s905x2"
-         ;;
-      10) FDTFILE="meson-g12a-x96-max-rmii.dtb"
-         UBOOT_OVERLOAD="u-boot-x96max.bin"
-         MAINLINE_UBOOT="/lib/u-boot/x96max-u-boot.bin.sd.bin"
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s905x2"
-         ;;
-      11) FDTFILE="meson-g12b-gtking.dtb"
-         UBOOT_OVERLOAD="u-boot-gtkingpro.bin"
-         MAINLINE_UBOOT="/lib/u-boot/gtking-u-boot.bin.sd.bin"
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s922x"
-         ;;
-      12) FDTFILE="meson-g12b-gtking-pro.dtb"
-         UBOOT_OVERLOAD="u-boot-gtkingpro.bin"
-         MAINLINE_UBOOT="/lib/u-boot/gtkingpro-u-boot.bin.sd.bin"
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s922x"
-         ;;
-      13) FDTFILE="meson-g12b-ugoos-am6.dtb"
-         UBOOT_OVERLOAD="u-boot-gtkingpro.bin"
-         MAINLINE_UBOOT="/lib/u-boot/gtkingpro-u-boot.bin.sd.bin"
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s922x"
-         ;;
-      14) FDTFILE="meson-g12b-gtking-pro-rev_a.dtb"
-         UBOOT_OVERLOAD="u-boot-odroid-n2.bin"
-         MAINLINE_UBOOT="/lib/u-boot/odroid-n2-u-boot.bin.sd.bin"
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s922x"
-         ;;
-      15) FDTFILE="meson-gxm-octopus-planet.dtb"
-         UBOOT_OVERLOAD="u-boot-zyxq.bin"
-         MAINLINE_UBOOT=""
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s912"
-         ;;
-      16) FDTFILE="meson-gxl-s905d-phicomm-n1.dtb"
-         UBOOT_OVERLOAD="u-boot-n1.bin"
-         MAINLINE_UBOOT=""
-         ANDROID_UBOOT="/lib/u-boot/u-boot-2015-phicomm-n1.bin"
-         AMLOGIC_SOC="s905d"
-         ;;
-      17) FDTFILE="meson-gxl-s905x-p212.dtb"
-         UBOOT_OVERLOAD="u-boot-p212.bin"
-         MAINLINE_UBOOT=""
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s905x"
-         ;;
-      18) FDTFILE="meson-gxl-s905w-tx3-mini.dtb"
-         UBOOT_OVERLOAD="u-boot-s905x-s912.bin"
-         MAINLINE_UBOOT=""
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC="s905w"
-         ;;
-      99) FDTFILE=${SPECIFY_DTB}
-         UBOOT_OVERLOAD=""
-         MAINLINE_UBOOT=""
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC=""
-         ;;
-      0) cat <<EOF
+
+if [ "$boxtype" == "99" ];then
+     FDTFILE=${SPECIFY_DTB}
+     UBOOT_OVERLOAD=""
+     MAINLINE_UBOOT=""
+     ANDROID_UBOOT=""
+     AMLOGIC_SOC=""
+else
+    ret=$(search_model $boxtype)
+    if [ "$ret" == "" ];then
+        echo "Input error, exit!"
+        exit 1
+    fi
+    # 3.  soc
+    # 4.  FDTFILE
+    # 5.  UBOOT_OVERLOAD
+    # 6.  MAINLINE_UBOOT
+    # 7.  ANDROID_UBOOT
+    AMLOGIC_SOC=$(echo "$ret" | awk -F ':' '{print $3}' | perl -pe 's/NA//;s/NULL//;s/\s+//g;')
+    FDTFILE=$(echo "$ret" | awk -F ':' '{print $4}' | perl -pe 's/NA//;s/NULL//;s/\s+//g;' )
+    UBOOT_OVERLOAD=$(echo "$ret" | awk -F ':' '{print $5}' | perl -pe 's/NA//;s/NULL//;s/\s+//g;')
+    MAINLINE_UBOOT=$(echo "$ret" | awk -F ':'  '{print $6}' | perl -pe 's/NA//;s/NULL//;s/\s+//g;')
+    ANDROID_UBOOT=$(echo "$ret" | awk -F ':' '{print $7}' | perl -pe 's/NA//;s/NULL//;s/\s+//g;')
+fi
+
+if [ "$FDTFILE" == "" ];then
+    cat <<EOF
 Please enter the .dtb file name of your box, do not include the path.
 For example: $FDTFILE
 EOF
-         echo  "Enter the .dtb File name:"
-         read  CUST_FDTFILE
-         FDTFILE=$CUST_FDTFILE
-         UBOOT_OVERLOAD=""
-         MAINLINE_UBOOT=""
-         ANDROID_UBOOT=""
-         AMLOGIC_SOC=""
-         ;;
-      *) echo "Input error, exit!"
-         exit 1
-         ;;
-esac
+    echo  "Enter the .dtb File name:"
+    read  CUST_FDTFILE
+    FDTFILE=$CUST_FDTFILE
+    UBOOT_OVERLOAD=""
+    MAINLINE_UBOOT=""
+    ANDROID_UBOOT=""
+    AMLOGIC_SOC=""
+fi
 
 echo -e "FDT Value [ ${FDTFILE} ]"
 
