tidy up codes

diff --git a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-swap b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-swap
--- a/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-swap
+++ b/amlogic-s9xxx/common-files/files/usr/sbin/openwrt-swap
@@ -10,7 +10,7 @@
 # Set the swap size in GB
 my_swap_gb="${1}"
 format_gb="$(echo "${my_swap_gb}" | awk -F "." '{print $1}')"
-if  [[ -n "$(echo "${format_gb}" | sed -n "/^[0-9]\+$/p")" ]]; then
+if [[ -n "$(echo "${format_gb}" | sed -n "/^[0-9]\+$/p")" ]]; then
     swap_gb="${format_gb}"
 else
     swap_gb="1"
@@ -18,24 +18,27 @@ fi
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ];then
+if [ "${ROOT_PTNAME}" == "" ]; then
     echo "Cannot find the partition corresponding to the root file system!"
     exit 1
 fi
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
 case ${ROOT_PTNAME} in
-       mmcblk?p[1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
-                      PARTITION_NAME="p"
-                      LB_PRE="EMMC_"
-                      ;;
-    [hsv]d[a-z][1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
-                      PARTITION_NAME=""
-                      LB_PRE=""
-                      ;;
-                   *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-                      exit 1
-                      ;;
+mmcblk?p[1-4])
+    EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
+    PARTITION_NAME="p"
+    LB_PRE="EMMC_"
+    ;;
+[hsv]d[a-z][1-4])
+    EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
+    PARTITION_NAME=""
+    LB_PRE=""
+    ;;
+*)
+    echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+    exit 1
+    ;;
 esac
 
 PARTITION_PATH="/mnt/${EMMC_NAME}${PARTITION_NAME}4"
@@ -44,7 +47,7 @@ if [ -z "$(echo "${available_space}" | sed -n "/^[0-9]\+$/p")" ]; then
     echo -e "The path is not available, the remaining space cannot be obtained."
     exit 1
 fi
-if  [[ "${available_space}" -lt "${swap_gb}" ]]; then
+if [[ "${available_space}" -lt "${swap_gb}" ]]; then
     echo -e "The remaining space is [ ${available_space} ] GB, and [ ${swap_gb} ] GB swap cannot be created."
     exit 1
 fi
@@ -57,7 +60,7 @@ echo -e "Prepare to create [ ${swap_gb} ] GB swap in the [ ${SWAP_PATH} ] direct
 # delete current swap
 delete_current_swap() {
     echo -e "Current swap size is: [ ${1} ] bytes, start to delete..."
-    current_swap_file="$( cat /proc/swaps | sed -n '$p' | awk '{print $1}' | echo $(xargs) )"
+    current_swap_file="$(cat /proc/swaps | sed -n '$p' | awk '{print $1}' | echo $(xargs))"
     swapoff ${current_swap_file} 2>/dev/null && sync
     rm -f ${current_swap_file} 2>/dev/null && sync
     echo -e "Delete successfully!"
@@ -66,7 +69,7 @@ delete_current_swap() {
 # create new swap
 create_new_swap() {
     echo -e "Start creating a new swap..."
-    dd_count=$((1000000*${swap_gb}))
+    dd_count=$((1000000 * ${swap_gb}))
     echo -e "The swap size is: [ ${swap_gb} ] GB, Please wait..."
     dd if=/dev/zero of=${SWAP_PATH}/swapfile bs=1024 count=${dd_count} conv=fsync && sync
     chmod 600 ${SWAP_PATH}/swapfile
@@ -84,7 +87,7 @@ create_new_swap() {
     echo -e "Current swap: \n$(cat /proc/swaps) \n"
 }
 
-current_swap="$( free -m | sed -n '$p' | awk '{print $2}' | echo $(xargs) )"
+current_swap="$(free -m | sed -n '$p' | awk '{print $2}' | echo $(xargs))"
 if [ "${current_swap}" -gt "0" ]; then
     delete_current_swap ${current_swap}
     create_new_swap ${swap_gb}
@@ -93,4 +96,3 @@ else
 fi
 sync
 exit 0
-
