update

diff --git a/amlogic-s9xxx/amlogic-kernel/build_kernel/openwrt-kernel b/amlogic-s9xxx/amlogic-kernel/build_kernel/openwrt-kernel
--- a/amlogic-s9xxx/amlogic-kernel/build_kernel/openwrt-kernel
+++ b/amlogic-s9xxx/amlogic-kernel/build_kernel/openwrt-kernel
@@ -268,41 +268,60 @@ replace_kernel() {
     echo -e "Package [ ${flippy_version} ] related files ..."
 
     tar -xzf ${P4_PATH}/${build_dtb} -C /boot/dtb/amlogic && sync
-    echo -e "Package [ ${P4_PATH}/${build_dtb} ] complete."
+    echo -e "Package [ ${build_dtb} ] complete."
 
     tar -xzf ${P4_PATH}/${build_boot} -C /boot && sync
-    echo -e "Package [ ${P4_PATH}/${build_boot} ] complete."
+    echo -e "Package [ ${build_boot} ] complete."
 
     tar -xzf ${P4_PATH}/${build_modules} -C /lib/modules && sync
-    echo -e "Package [ ${P4_PATH}/${build_modules} ] complete."
-
+    echo -e "Package [ ${build_modules} ] complete."
+    
     sleep 3
 
-    chmod 777 /boot/uInitrd-* 2>/dev/null
+    if [ "$( ls /boot/dtb/amlogic -l 2>/dev/null | grep "^-" | wc -l )" -ge "10" ]; then
+        echo -e "01. /boot/dtb/amlogic files complete."
+    fi
+    sleep 3
+
+    chmod 777 /boot/uInitrd-${flippy_version} 2>/dev/null
     [ -f /boot/uInitrd ] && rm -f /boot/uInitrd 2>/dev/null && sync
-    if [ -f /boot/uInitrd-* ]; then
-        mv -f /boot/uInitrd-* /boot/uInitrd 2>/dev/null && sync
+    if [ -f /boot/uInitrd-${flippy_version} ]; then
+        mv -f /boot/uInitrd-${flippy_version} /boot/uInitrd 2>/dev/null && sync
         if [ ! -f /boot/uInitrd ]; then
             die "/boot/uInitrd file is missing."
         fi
     else
-        die "/boot/uInitrd-* file is missing."
+        die "/boot/uInitrd-${flippy_version} file is missing."
     fi
 
-    chmod 777 /boot/vmlinuz-* 2>/dev/null
+    chmod 777 /boot/vmlinuz-${flippy_version} 2>/dev/null
     [ -f /boot/zImage ] && rm -f /boot/zImage 2>/dev/null && sync
-    if [ -f /boot/vmlinuz-* ]; then
-        mv -f /boot/vmlinuz-* /boot/zImage 2>/dev/null && sync
+    if [ -f /boot/vmlinuz-${flippy_version} ]; then
+        mv -f /boot/vmlinuz-${flippy_version} /boot/zImage 2>/dev/null && sync
         if [ ! -f /boot/zImage ]; then
             die "/boot/zImage file is missing."
         fi
     else
-        die "/boot/vmlinuz-* file is missing."
+        die "/boot/vmlinuz-${flippy_version} file is missing."
     fi
 
-    cd /lib/modules/*/
+    [ -f /boot/config-${flippy_version} ] || die "/boot/config-${flippy_version} file is missing."
+    [ -f /boot/System.map-${flippy_version} ] || die "/boot/System.map-${flippy_version} file is missing."
+    echo -e "02. /boot five files complete."
+    sleep 3
+
+    cd /lib/modules/${flippy_version}/
     rm -f *.ko 2>/dev/null
     find ./ -type f -name '*.ko' -exec ln -s {} ./ \;
+    sync && sleep 3
+    x=$( ls *.ko -l 2>/dev/null | grep "^l" | wc -l )
+    if [ "${x}" -eq "0" ]; then
+        die "Error *.ko Files not found."
+    else
+        echo -e "03. /lib/modules/ files complete."
+    fi
+    sleep 3
+
     rm -rf ${P4_PATH}/dtb-amlogic-*.tar.gz ${P4_PATH}/boot-*.tar.gz ${P4_PATH}/modules-*.tar.gz 2>/dev/null
     sync
 
