Update Docker workflow

diff --git a/.github/workflows/build-openwer-docker-image.yml b/.github/workflows/build-openwer-docker-image.yml
--- a/.github/workflows/build-openwer-docker-image.yml
+++ b/.github/workflows/build-openwer-docker-image.yml
@@ -48,18 +48,38 @@ jobs:
         if: (!cancelled())
         run: |
           # Get OpenWrt file
-          openwrt_url="$(curl \
-                            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                            -s "https://api.github.com/repos/${{ github.repository }}/releases?per_page=20" |
-                            grep -o "OpenWrt_.*${{ inputs.source_branch }}.*/.*rootfs.tar.gz" |
-                            sort -urV |
-                            head -n 1
-                        )"
-          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
+          latest_version=$(curl -s \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              https://api.github.com/repos/${{ github.repository }}/releases?per_page=20 | \
+              jq -r --arg RTK "OpenWrt_${{ inputs.source_branch }}_save_" \
+              --arg BOARD "rootfs" \
+              '[.[] | select(.tag_name | contains($RTK))] |
+              map(.assets[] | select(.name | contains($BOARD) and endswith(".tar.gz"))) |
+              sort_by(.updated_at) |
+              reverse |
+              .[0] |
+              {data: .updated_at, url: .url, name: .name}')
 
+          [[ -z "${latest_version}" || "${latest_version}" == "null" ]] && {
+              echo "Invalid OpenWrt rootfs file download address."
+              exit 1
+          }
+
+          # Get URL and filename separately
+          latest_url="$(echo ${latest_version} | jq -r '.url')"
+          openwrt_filename="$(echo ${latest_version} | jq -r '.name')"
+
+          # Download using API method (add octet-stream header)
+          echo "Downloading: ${openwrt_filename}"
           [[ -d "openwrt" ]] || mkdir -p openwrt
-          curl -fsSL "https://github.com/${{ github.repository }}/releases/download/${openwrt_url}" -o "openwrt/openwrt-armsr-armv8-generic-rootfs.tar.gz"
-          [[ "${?}" -ne "0" ]] && echo "OpenWrt file download failed." && exit 1
+          curl -fsSL \
+               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+               -H "Accept: application/octet-stream" \
+               "${latest_url}" \
+               -o "openwrt/${openwrt_filename}"
+          [[ "${?}" -ne "0" ]] && echo "Download failed." && exit 1
+
           echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Build the Docker image
