Optimizing rootfs file download for Docker

diff --git a/.github/workflows/build-the-docker-image-of-openwrt.yml b/.github/workflows/build-the-docker-image-of-openwrt.yml
--- a/.github/workflows/build-the-docker-image-of-openwrt.yml
+++ b/.github/workflows/build-the-docker-image-of-openwrt.yml
@@ -45,18 +45,28 @@ jobs:
         id: down
         if: (!cancelled())
         run: |
-          # Get OpenWrt file
-          openwrt_url="$(curl \
-                            --header "authorization: Bearer ${{ secrets.GH_TOKEN }}" \
-                            -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" |
-                            grep -o "OpenWrt_.*${{ inputs.source_branch }}.*/.*rootfs.tar.gz" |
-                            head -n 1
-                        )"
-          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
+          armvirt_tarfile_path="openwrt"
+          armvirt_tarfile_name="openwrt-armvirt-64-default-rootfs.tar.gz"
+          [[ -d "${armvirt_tarfile_path}" ]] || mkdir -p ${armvirt_tarfile_path}
 
-          [[ -d "openwrt" ]] || mkdir -p openwrt
-          wget -q "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}" -O "openwrt/openwrt-armvirt-64-default-rootfs.tar.gz"
-          [[ "${?}" -ne "0" ]] && echo "OpenWrt file download failed." && exit 1
+          latest_version="$(curl -s \
+                              -H "Accept: application/vnd.github+json" \
+                              -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
+                              https://api.github.com/repos/${GITHUB_REPOSITORY}/releases |
+                              jq '.[]' |
+                              jq -s --arg RTK "OpenWrt_${{ inputs.source_branch }}_" '.[] | select(.tag_name | contains($RTK))' |
+                              jq -s '.[].assets[] | {data:.updated_at, url:.browser_download_url}' |
+                              jq -s --arg BOARD "-rootfs.tar.gz" '.[] | select(.url | endswith($BOARD))' |
+                              jq -s 'sort_by(.data)|reverse[]' |
+                              jq -s '.[0]' -c
+                          )"
+
+          [[ "${latest_version}" == "null" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
+          latest_updated_at="$(echo ${latest_version} | jq -r '.data')"
+          latest_url="$(echo ${latest_version} | jq -r '.url')"
+
+          wget -q -O "${armvirt_tarfile_path}/${armvirt_tarfile_name}" "${latest_url}"
+          [[ "${?}" -ne "0" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
           echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Build the Docker image
