Optimize Actions code

diff --git a/.github/workflows/push-openwrt-to-docker-hub.yml b/.github/workflows/push-openwrt-to-docker-hub.yml
--- a/.github/workflows/push-openwrt-to-docker-hub.yml
+++ b/.github/workflows/push-openwrt-to-docker-hub.yml
@@ -11,8 +11,8 @@ on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      openwrt_file:
-        description: "Select the OpenWrt rootfs file"
+      branch:
+        description: "Select the source branch"
         required: false
         default: "lede"
         type: choice
@@ -41,19 +41,18 @@ jobs:
         if: (!cancelled())
         run: |
           # Get OpenWrt file
-          openwrt_file="${{ github.event.inputs.openwrt_file }}"
-          openwrt_url="$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_s9xxx_${openwrt_file}.*/.*rootfs.tar.gz" | head -n 1)"
-          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found." && exit 1
+          openwrt_url="$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_.*${{ github.event.inputs.branch }}.*/.*rootfs.tar.gz" | head -n 1)"
+          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
           rm -rf ${{ env.DOCKER_OUTPATH }} 2>/dev/null && mkdir -p ${{ env.DOCKER_OUTPATH }}
-          wget -q "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}" -O ${{ env.DOCKER_OUTPATH }}/openwrt-armvirt-64-default-rootfs.tar.gz
-
+          wget -q "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}" -O "${{ env.DOCKER_OUTPATH }}/openwrt-armvirt-64-default-rootfs.tar.gz"
+          #
           # Generate Dockerfile
           docker_envfile="${{ env.DOCKER_OUTPATH }}/Dockerfile"
           echo 'FROM scratch' >${docker_envfile}
           echo 'ADD openwrt-armvirt-64-default-rootfs.tar.gz /' >>${docker_envfile}
           echo 'EXPOSE 22 53 80 443 7681' >>${docker_envfile}
           echo 'ENTRYPOINT ["/sbin/init"]' >>${docker_envfile}
-
+          #
           sync && echo -e "Current ${{ env.DOCKER_OUTPATH }} directory status: \n$(ls ${{ env.DOCKER_OUTPATH }} -l)"
           echo "::set-output name=status::success"
 
diff --git a/.github/workflows/use-releases-file-to-packaging.yml b/.github/workflows/use-releases-file-to-packaging.yml
--- a/.github/workflows/use-releases-file-to-packaging.yml
+++ b/.github/workflows/use-releases-file-to-packaging.yml
@@ -11,7 +11,7 @@ on:
   workflow_dispatch:
     inputs:
       branch:
-        description: "Select the packaged source branch"
+        description: "Select the source branch"
         required: false
         default: "lede"
         type: choice
@@ -19,7 +19,7 @@ on:
           - lede
           - official
       openwrt_soc:
-        description: "Select Amlogic SoC"
+        description: "Select device SoC"
         required: false
         default: "all"
         type: choice
@@ -85,25 +85,21 @@ jobs:
           sudo -E apt-get -qq install $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
           sudo -E apt-get -qq autoremove --purge
           sudo -E apt-get -qq clean
-          sudo timedatectl set-timezone "$TZ"
-          # Input value validation
-          ARR_BRANCH=("official" "lede")
-          if [[ -n "${{ github.event.inputs.branch }}" && -n "$(echo "${ARR_BRANCH[@]}" | grep -w "${{ github.event.inputs.branch }}")" ]]; then
-            RELEASES_BRANCH=${{ github.event.inputs.branch }}
-          else
-            RELEASES_BRANCH=lede
-          fi
-          echo "RELEASES_BRANCH=${RELEASES_BRANCH}" >> $GITHUB_ENV
+          sudo timedatectl set-timezone "${TZ}"
           echo "COMPILE_STARTINGTIME=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV
 
       - name: Download OpenWrt Armvirt firmware
         id: down
         if: (!cancelled())
         run: |
+          openwrt_url="$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_.*${{ github.event.inputs.branch }}.*/.*rootfs.tar.gz" | head -n 1)"
+          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
+          #
           armvirt_tarfile_path="openwrt/bin/targets/armvirt/64"
-          [ -d "${armvirt_tarfile_path}" ] || mkdir -p ${armvirt_tarfile_path}
-          curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_s9xxx_${{ env.RELEASES_BRANCH }}.*/.*rootfs.tar.gz" | head -n 1 > DOWNLOAD_ARMVIRT
-          [ -s DOWNLOAD_ARMVIRT ] && wget -q -P ${armvirt_tarfile_path} https://github.com/${GITHUB_REPOSITORY}/releases/download/$(cat DOWNLOAD_ARMVIRT)
+          [[ -d "${armvirt_tarfile_path}" ]] || mkdir -p ${armvirt_tarfile_path}
+          #
+          wget -q -P "${armvirt_tarfile_path}" "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}"
+          [[ "${?}" -ne "0" ]] && echo "The armvirt file download failed!" && exit 1
           echo "::set-output name=status::success"
 
       - name: Build OpenWrt firmware
@@ -120,7 +116,7 @@ jobs:
         uses: ncipollo/release-action@main
         if: env.PACKAGED_STATUS == 'success' && !cancelled()
         with:
-          tag: openwrt_s9xxx_${{ env.RELEASES_BRANCH }}_${{ env.PACKAGED_OUTPUTDATE }}
+          tag: openwrt_amlogic_s9xxx_${{ github.event.inputs.branch }}_${{ env.PACKAGED_OUTPUTDATE }}
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           token: ${{ secrets.GH_TOKEN }}
